config/routes.rb
Rails.application.routes.draw do
  post 'top/login'
  get 'top/logout'
  get 'mypages/index'
  get 'users/index'
  get 'groups/new'
  #get 'groups/:e.id', to: 'groups#show', as:'show'
  root 'users#index'
  resources :users
  resources :groups
  resources :calendars
  resources :events
  resources :joins, only: [:create, :destroy]
  resources :groups do
    resources :events
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/calendar.rb
class Calendar < ApplicationRecord
    belongs_to :event
    belongs_to :group
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :calendars
    has_many :groups
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :joins,dependent: :destroy
    has_many :calendars, dependent: :destroy
    has_many :events, through: :groupcalendars
    has_many :events, through: :calendars
    has_many :join_users, through: :joins, source: :user
    has_many :calendar_groups, through: :calendars, source: :event
    
    def join(user)
        joins.create(user_id: user.id)
    end
    
    def unjoin(user)
        joins.find_by(user_id: user.id).destroy
    end

    def joined?(user)
        join_users.include?(user)
    end
    
    def member_count
        join_users.count
    end
    
    def member_names
        join_users.pluck(:uid).join(', ')
    end
    
    
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
    belongs_to :user
    belongs_to :group
end

app/models/join.rb
class Join < ApplicationRecord
    belongs_to :user
    belongs_to :group
end

app/models/top.rb
class Top < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_many :joins
    has_many :groups
    has_many :join_groups, through: :joins, source: :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    before_action :set_group_id_in_session
    
    private
    def current_user
        if session[:login_uid]
            User.find_by(uid: session[:login_uid])
        end
    end
    
    def set_group_id_in_session
        session[:group_id] = params[:group_id] if params[:group_id].present?
    end

end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_group
  
  def index
    @events = Event.all
    @group_events = @group.calendar_groups
    @event = Event.new
  end
  
  def new
    @event = Event.new
  end

  def show
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.create(event_parameter)
    if @event.save
      @calendar = Calendar.new(group_id: @group.id, event_id: @event.id)
      @calendar.save
      redirect_to event_path(@event)
    end
  end
  
  def show
    @event = Event.find(params[:id])
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end
  
  def edit
    @event = Event.find(params[:id])
  end
  
  def update
    @event = Event.find(params[:id])
    if @event.update(event_parameter)
      redirect_to event_path(@event), notice: 'イベントが更新されました。'
    else
      render :edit
    end
  end
  
  private

  def event_parameter
    params.require(:event).permit(:content, :comment, :start_time)
  end
  
  def set_group
    @group = Group.find_by(id: params[:group_id] || session[:group_id])
  end
  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
    
    def index
        @groups = Group.all
        @joins = Join.where(group_id: params[:group_id])
    end
    
    def new
        @group = Group.new
    end
    
    def create
        @group = Group.new(name: params[:group][:name])
        if @group.save
            redirect_to groups_path
        else
            render 'new'
        end
    end

    def edit
        @group = Group.find(params[:id])
    end
    
    def destroy
        Group.find(params[:id]).destroy
        redirect_to groups_path
    end
    
    def joingroup
        group = Group.find(params[:group_id])
        pass = Group.find(params[:group_pass])
        unless group.joined?(current_user) and pass.joined?(:g_pass)
            group.join(current_user)
        end
        redirect_to groups_path
    end
    
end

app/controllers/joins_controller.rb
class JoinsController < ApplicationController
    def create
        
        group = Group.find(params[:group_id])
        unless group.joined?(current_user)
            group.join(current_user)
        end
        #user = User.find_by(uid:session[:login_uid])
        #user.join_groups << group
        redirect_to groups_path
    end
    
    def destroy
        group = Group.find(params[:id])
        if group.joined?(current_user)
            group.unjoin(current_user)
        end
        #user = User.find_by(uid: session[:login_uid])
        #group.joins.find_by(user_id: user.id).destroy
        redirect_to groups_path
    end
end

    def login
        user = User.find_by(uid: params[:uid])
        if user != nil
            login_password = BCrypt::Password.new(user.pass)
        if login_password == params[:pass]
            session[:login_uid] = user.uid
            redirect_to mypages_index_path
        else
          render "error"
        end
        end
    end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
    def index
      @user = User.find_by(uid: session[:login_uid])
      @groups = Group.all
      @user_groups = @user.join_groups.order(:name)
    end
    
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    if session[:login_uid] != nil
      render "main"
    else
      render "login"
    end
  end

  def login
    user = User.find_by(uid: params[:uid])
    if user != nil
        login_password = BCrypt::Password.new(user.pass)
        if login_password == params[:pass]
          session[:login_uid] = user.uid
          redirect_to mypages_index_path
        else
          render "error"
        end
    end
  end
  
  def logout
    session.delete(:login_uid)
    redirect_to root_path
  end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end
  
  def create
    upass = BCrypt::Password.create(params[:user][:pass])
    user = User.new(uid: params[:user][:uid],pass: upass)
    user.save
    redirect_to users_path
  end
  
  def destroy
    User.find(params[:id]).destroy
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_date_class(date)
    "current-date" if date == Date.current
  end
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/joins_helper.rb
module JoinsHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_sidebar.html.erb
    <div class="menu-container">
        <input type="checkbox" id="menu-toggle">
        <nav class="menu">
            <ul>
                <li><a href="#"><%= link_to 'ホーム画面へ' ,mypages_index_path %></a></li>
                <li><a href="#"><%= link_to 'グループ作成', groups_new_path %></a></li>
                <li><a href="#"><%= link_to 'グループ一覧', groups_path %></a></li>
                <li><a href="#"><%= link_to 'ログアウト' , top_logout_path%></a></li>
            </ul>
        </nav>
        <label for="menu-toggle" class="menu-button">
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
        </label>
    </div>

app/views/events/edit.html.erb
<div class="main">
  <div id="contents1">
    <%= render "sidebar" %>
  </div>
  <div class="contents2">
    <h1>編集画面</h1>
<%= form_with(model: @event, local: true) do |form| %>
  <div class="content">
    <div class="form-tag">内容</div>
    <%= form.text_field :content %>
  </div>
  
  <div class="comment">
    <div class="form-tag">コメント</div>
    <%= form.text_field :comment %>
  </div>
  
  <div class="time">
    <div class="form-tag">時間</div>
    <%= form.datetime_select :start_time %>
  </div>


  <div class="submit">
    <%= form.submit %>
  </div>

<% end %>
</div>
</div>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<div class="main">
<div id="contents1">
  <%= render "sidebar" %>
</div>

<div class="contents2">
  <h1><%= @group.name %>カレンダー</h1>
</div>

<hr>

<table class="group-table">
  <tr>
    <th>タイトル</th>
    <th>日程</th>
    <th>時間</th>
    <th>コメント</th>
  </tr>
    <% @group_events.each do |event| %>
      <tr>
        <td><%= link_to event.content, event %></td>
        <td><%= event.start_time.strftime("%m-%d") %></td>
        <td><%= event.start_time.strftime("%H:%M") %></td>
        <td><%= event.comment %></td>
      </tr>
    <% end %>
</table>

<hr>

  <div class="col-md-8">
    <%= month_calendar events: @group_events do |date, events| %>
      <%= date.day %>

      <% events.each do |event| %>
        <div>
          <%= link_to event.content, event%>
        </div>
      <% end %>
    <% end %>
  </div>

<hr>

<%= form_with(model: @event, local: true) do |form| %>

  <div class="content">
    <div class="form-tag">内容</div>
    <%= form.text_field :content %>
  </div>
  
  <div class="comment">
    <div class="form-tag">コメント</div>
    <%= form.text_field :comment %>
  </div>

  <div class="time">
    <div class="form-tag">時間</div>
    <%= form.datetime_select :start_time %>
  </div>

 <div class="submit">
    <%= form.submit %>
 </div>
<% end %>
</div>
</div>

<%=link_to '戻る', groups_path ,class:"custom-submit-button" %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<div class="main">
  <div id="contents1">
    <%= render "sidebar" %>
  </div>
  
  <div class="contents2">
    <h1>予定</h1>
    <p>
      <strong>内容</strong>
      <%= @event.content %>
    </p>

    <p>
      <strong>日時</strong>
      <%= @event.start_time.strftime("%m-%d") %>
    </p>
    
    <p>
      <strong>コメント</strong>
      <%= @event.comment %>
    </p>

    <%= link_to '編集', edit_event_path(@event), class: "custom-submit-button" %>
    <%= link_to '消去', event_path(@event.id), data: {"turbo-method": :delete} ,class:"custom-submit-button"%>
    <%= link_to '戻る', events_path ,class:"custom-submit-button"%>
  </div>
</div>

app/views/groups/edit.html.erb
<%= render 'form', group: @group %>

app/views/groups/index.html.erb
<div class="main">
    
    <div id="contents1">
        <%= render "sidebar" %>
    </div>
    
    <div class="contents2">
        <h1>グループ画面</h1>
    </div>
    <p class="margin"></p>
    <table class="group-table">
    <tr>
      <th>グループ名</th>
      <th>メンバー数</th>
      <th>メンバー名</th>
      <th>削除</th>
      <th>状態</th>
    </tr>

    <% @groups.each do |e| %>
      <tr>
        <td>
          <% if e.joined?(current_user) %>
              <%= link_to e.name, group_events_path(e), data: { group_id: e.id} %>
            <% else %>
              <%=e.name%>
          <% end %>  
        </td>
        <td><%= e.member_count %></td>
        <td><%= e.member_names %></td>
        <td>
          <% if e.joined?(current_user) %>
          <%= link_to '削除', group_path(e), data: {"turbo-method": :delete} %>
          <% end %>
        </td>
        <td>
            <% if e.joined?(current_user) %>
              <%= link_to '退会', join_path(e), data: {"turbo-method": :delete} %>
            <% else %>
        <%= link_to '加入', joins_path(group_id: e.id), data: {"turbo-method": :post} %>
            <% end %>
        </td>
      </tr>
    <% end %>
    </table>

    <p><%=link_to '戻る', mypages_index_path ,class:"custom-submit-button"%></p>
    <p><%= link_to 'グループ作成', new_group_path ,class:"custom-submit-button"%></p>
</div>

app/views/groups/new.html.erb
<div class="main">
    
    <div id="contents1">
        <%= render "sidebar" %>
    </div>
    
    <div class="contents2">
        <h1>グループ作成</h1>
        <p class="dashed"></p>
        <%= form_for @group, url: {action: :create} do |f| %>
            <p>
                <%= f.label :name, 'グループ名' %>
                <%= f.text_field :name %>
            </p>
          <%= f.submit '登録', class:"custom-submit-button"%>
          <% end %>
        <%=link_to '戻る', groups_path %>
    </div>
</div>

app/views/groups/show.html.erb
<div class="main">
    
    <div id="contents1">
        <%= render "sidebar" %>
    </div>
    
    <div class="contents2">
        <h1>グループ加入</h1>
    <%= form_tag '/groups/joingroup', method: :post do %>
          <p>
              <%= label_tag :group_id, 'グループ名' %>
              <%= text_field_tag :group_id%>
          </p>
          <p>
              <%= label_tag :g_pass, 'パスワード' %>
              <%= password_field_tag :g_pass %>
          </p>
          <%= submit_tag '加入',class:"custom-submit-button" %>
        <% end %>
        <%=link_to '戻る', mypages_index_path %>
    </div>
</div>

app/views/users/index.html.erb
<h1>ログイン画面</h1>
<%= form_tag '/top/login', method: :post do %>
  <p>
      <%= label_tag :uid, 'ユーザー名' %>
      <%= text_field_tag :uid %>
  </p>
  <p>
      <%= label_tag :pass, 'パスワード' %>
      <%= password_field_tag :pass %>
  </p>
  <%= submit_tag 'ログイン',class:"custom-submit-button" %>
<% end %>

<% @users.each do |e| %>
    <p>
        ユーザー名：<%= e.uid %>
        <%= link_to '削除', user_path(e), data: {"turbo-method": :delete} %><br>
    </p>
<% end %>
<%= link_to '新規追加', new_user_path %>

app/views/users/new.html.erb
<h1>ユーザー登録</h1>
<p class="dashed"></p>
<%= form_for @user,url: {action: :create} do |f| %>
    <P>
        <%= f.label :uid, 'ユーザーID' %>
        <%= f.text_field :uid %>
    </P>
    <p>
        <%= f.label :pass, 'パスワード' %>
        <%= f.password_field :pass %>
    </p>
    <%= f.submit '登録',class:"custom-submit-button" %>
<% end %>

<%=link_to '戻る', :back%>